import Head from 'next/head';
import Sidebar from '../components/Sidebar.js';

export default function Home() {
  return (
    <>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/WhatsApp.svg/800px-WhatsApp.svg.png?v=1" />
      </Head>
      <Sidebar/>
    </>
  )
}
